name: nicoya_now
description: "Una aplicación de delivery para Nicoya"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Base de datos en la nube
  supabase_flutter: ^1.10.25
  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.8.3
  # Dependencias para Turso/LibSQL
  http: ^1.1.2
  # Utilidades
  rxdart: ^0.27.7
  connectivity_plus: ^5.0.2
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
